version: "3"
services:
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root 
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - '27017:27017'
    volumes:
      - stellerom-db:/data/db
volumes:
  stellerom-db:

