// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $about from "./routes/about.tsx";
import * as $index from "./routes/index.tsx";
import * as $new_review from "./routes/new-review.tsx";
import * as $new_room from "./routes/new-room.tsx";
import * as $profile from "./routes/profile.tsx";
import * as $rooms_id_ from "./routes/rooms/[id].tsx";
import * as $EditRoom from "./islands/EditRoom.tsx";
import * as $Map from "./islands/Map.tsx";
import * as $RangeInput from "./islands/RangeInput.tsx";
import * as $SimpleMap from "./islands/SimpleMap.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/about.tsx": $about,
    "./routes/index.tsx": $index,
    "./routes/new-review.tsx": $new_review,
    "./routes/new-room.tsx": $new_room,
    "./routes/profile.tsx": $profile,
    "./routes/rooms/[id].tsx": $rooms_id_,
  },
  islands: {
    "./islands/EditRoom.tsx": $EditRoom,
    "./islands/Map.tsx": $Map,
    "./islands/RangeInput.tsx": $RangeInput,
    "./islands/SimpleMap.tsx": $SimpleMap,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
