name: app-cicd
on:
  push:
    paths:
      - app/**
      - .github/workflows/app.yaml

permissions:
  id-token: write # Needed for auth with Deno Deploy
  contents: read # Needed to clone the repository

jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    environment: Development
    env:
      AZURE_ADB2C_CLIENT_ID: ${{ vars.AZURE_ADB2C_CLIENT_ID }}
      AZURE_ADB2C_CLIENT_SECRET: ${{ secrets.AZURE_ADB2C_CLIENT_SECRET }}
      AZURE_ADB2C_TENANT_ID: ${{ vars.AZURE_ADB2C_TENANT_ID }}
      AZURE_ADB2C_DOMAIN: stellerom.ciamlogin.com
      AZURE_ADB2C_POLICY: ""

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build step
        run: deno task build
        working-directory: app

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "stellerom-dev"
          entrypoint: "main.ts"
          root: "app"


  deploy_prod:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: deploy_dev
    runs-on: ubuntu-latest
    environment: Production
    env:
      AZURE_ADB2C_CLIENT_ID: ${{ vars.AZURE_ADB2C_CLIENT_ID }}
      AZURE_ADB2C_CLIENT_SECRET: ${{ secrets.AZURE_ADB2C_CLIENT_SECRET }}
      AZURE_ADB2C_TENANT_ID: ${{ vars.AZURE_ADB2C_TENANT_ID }}
      AZURE_ADB2C_DOMAIN: stellerom.ciamlogin.com
      AZURE_ADB2C_POLICY: ""

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build step
        run: deno task build
        working-directory: app

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "christianfosli-stellerom"
          entrypoint: "main.ts"
          root: "app"
          
          
