name: review-api-cicd

on:
  push:
    paths:
      - review-api/**
      - .github/workflows/review-api.yaml
      - scripts/az-bootstrap-containerapp.bash
  workflow_dispatch:

permissions:
  # required for federated credentials to access azure
  id-token: write
  # required for federated credentials to access azure
  contents: read
  # required to push to ghcr
  packages: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          tags="-t ghcr.io/christianfosli/stellerom/review-api:${{ github.sha }}"
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            printf 'Banch is main! Tagging with latest\n'
            tags="$tags -t ghcr.io/christianfosli/stellerom/review-api:latest"
          fi
          cd review-api
          docker build $tags .
        env:
          DOCKER_BUILDKIT: "1"

      - name: Push
        run: |
          docker push --all-tags ghcr.io/christianfosli/stellerom/review-api

  deploy_dev:
    needs: build
    runs-on: ubuntu-22.04
    environment: Development
    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZ_CLIENT_ID }}
          tenant-id: ${{ secrets.AZ_TENANT_ID }}
          subscription-id: ${{ secrets.AZ_SUBS_ID }}

      - name: Infra
        run: ./scripts/az-bootstrap-containerapp.bash
        env:
          ENVIRONMENT: dev
          SERVICE_NAME: review-api
          TARGET_PORT: 3001

      - name: Deploy
        run: |
          set -eo pipefail

          az containerapp secret set -n capp-stellerom-review-api-dev -g rg-stellerom-dev \
            --secrets "db-connstr=$DB_CONNSTR"

          az containerapp update -n capp-stellerom-review-api-dev -g rg-stellerom-dev \
            --image ghcr.io/christianfosli/stellerom/review-api:${{ github.sha }} \
            --min-replicas 0 --max-replicas 2 \
            --set-env-vars "REVIEW_API_DB_CONNSTR=secretref:db-connstr" "REVIEW_API_DB_NAME=review-api-dev" \
            "ROOM_API_URL=https://room-api-dev.stellerom.no" \
            "ALLOWED_IMAGE_BASE_URLS='["https://ststelleromdev.blob.core.windows.net"]'"
        env:
          DB_CONNSTR: "mongodb+srv://${{ secrets.REVIEW_API_DB_USERNAME }}:${{ secrets.REVIEW_API_DB_PASSWORD}}@azure-stellerom.au87e49.mongodb.net"

  deploy_prod:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: deploy_dev
    runs-on: ubuntu-22.04
    environment: Production
    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZ_CLIENT_ID }}
          tenant-id: ${{ secrets.AZ_TENANT_ID }}
          subscription-id: ${{ secrets.AZ_SUBS_ID }}

      - name: Infra
        run: ./scripts/az-bootstrap-containerapp.bash
        env:
          ENVIRONMENT: prod
          SERVICE_NAME: review-api
          TARGET_PORT: 3001

      - name: Deploy
        run: |
          az containerapp secret set -n capp-stellerom-review-api-prod -g rg-stellerom-prod \
            --secrets "db-connstr=$DB_CONNSTR"

          az containerapp update -n capp-stellerom-review-api-prod -g rg-stellerom-prod \
            --image ghcr.io/christianfosli/stellerom/review-api:${{ github.sha }} \
            --min-replicas 1 --max-replicas 5 \
            --set-env-vars "REVIEW_API_DB_CONNSTR=secretref:db-connstr" "REVIEW_API_DB_NAME=review-api-prod" \
            "ROOM_API_URL=https://room-api-prod.stellerom.no" \
            "ALLOWED_IMAGE_BASE_URLS='["https://ststelleromprod.blob.core.windows.net"]'"
        env:
          DB_CONNSTR: "mongodb+srv://${{ secrets.REVIEW_API_DB_USERNAME }}:${{ secrets.REVIEW_API_DB_PASSWORD}}@azure-stellerom.au87e49.mongodb.net"
